import type { UsageDigest } from "@claude-proxy/core";
import { fmtInt, fmtPct, fmtUsd } from "./format";

/** One Overview statistic, shared by the cards, their mini charts, and `/trends/$metric`. */
export interface StatMetric {
  /** URL slug for `/trends/$metric` and the key used across the app. */
  key: string;
  /** Card caption. */
  label: string;
  /** Heading on the large-scale trend page (defaults to `label`). */
  title?: string;
  /** One-line explanation shown on the trend page. */
  description: string;
  /** Line/plot colour (a CSS custom property). */
  color: string;
  /** Formats a plotted value for axes, tooltips, and the popover. */
  format: (n: number) => string;
  /** The value plotted for a single day. */
  value: (d: UsageDigest) => number;
  /** The card's headline for today; defaults to `format(value(d))`. */
  headline?: (d: UsageDigest) => string;
  /** Small caption under the headline. */
  sub?: (d: UsageDigest) => string | undefined;
  /** Whether a rising value is a regression (cost, tokens) vs. a win (cache). */
  increaseIsBad?: boolean;
  /** Matching field in `UsageDigest.trend` for the day-over-day delta chip. */
  trendField?: string;
}

const fmtBytesLabel = (n: number) => `${fmtInt(n)} B`;

/** The Overview statistics, in the order they appear on the page. */
export const METRICS: StatMetric[] = [
  {
    key: "real-input",
    label: "Real input tokens",
    description: "Non-cached input tokens sent to the model each day.",
    color: "var(--accent)",
    format: fmtInt,
    value: (d) => d.tokens.realInput,
    trendField: "realInput",
  },
  {
    key: "output",
    label: "Output tokens",
    description: "Tokens generated by the model each day.",
    color: "var(--good)",
    format: fmtInt,
    value: (d) => d.tokens.output,
    trendField: "output",
  },
  {
    key: "cost",
    label: "Est. cost",
    description: "Approximate USD spend per day, from token counts and model pricing.",
    color: "var(--accent-2)",
    format: fmtUsd,
    value: (d) => d.cost.total,
    sub: () => "approx.",
    trendField: "cost",
  },
  {
    key: "cache-hit",
    label: "Cache-hit ratio",
    description: "Share of prompt tokens served from cache (cacheRead / realInput) each day.",
    color: "var(--signal)",
    format: (n) => fmtPct(n),
    value: (d) => d.tokens.cacheHitRatio * 100,
    increaseIsBad: false,
  },
  {
    key: "requests",
    label: "Requests",
    description: "Requests captured per day.",
    color: "var(--good)",
    format: fmtInt,
    value: (d) => d.requestCount,
    trendField: "requestCount",
  },
  {
    key: "busiest-hour",
    label: "Busiest hour",
    title: "Busiest-hour requests",
    description: "Requests during the single busiest UTC hour of each day.",
    color: "var(--accent)",
    format: (n) => `${fmtInt(n)} req`,
    value: (d) => d.busiestHour?.requestCount ?? 0,
    headline: (d) => (d.busiestHour ? `${String(d.busiestHour.hour).padStart(2, "0")}:00` : "—"),
    sub: (d) => (d.busiestHour ? `${d.busiestHour.requestCount} req · UTC` : undefined),
  },
  {
    key: "tool-overhead",
    label: "Tool overhead",
    description: "Estimated tool-schema tokens as a percentage of input tokens each day.",
    color: "var(--amber)",
    format: (n) => fmtPct(n),
    value: (d) => d.toolOverheadPctOfInput,
    sub: () => "of input tokens",
  },
  {
    key: "avg-system-prompt",
    label: "Avg system prompt",
    description: "Mean system-prompt size (bytes) per request each day.",
    color: "var(--amber)",
    format: fmtBytesLabel,
    value: (d) => d.avgSystemPromptBytes,
  },
];

const BY_KEY = new Map(METRICS.map((m) => [m.key, m]));

/** Look up a metric by its URL slug. */
export const findMetric = (key: string): StatMetric | undefined => BY_KEY.get(key);
