import { costPerMTok, reportTzAbbr, type UsageDigest } from '@claude-proxy/core';
import { fmtBytes, fmtCompact, fmtInt, fmtPct, fmtUsd, fmtUsdCompact, fmtUsdPerMTok } from './format';

/** One Overview statistic, shared by the cards, their mini charts, and `/trends/$metric`. */
export interface StatMetric {
  /** URL slug for `/trends/$metric` and the key used across the app. */
  key: string;
  /** Card caption. */
  label: string;
  /** Heading on the large-scale trend page (defaults to `label`). */
  title?: string;
  /** One-line explanation shown on the trend page. */
  description: string;
  /** Line/plot colour (a CSS custom property). */
  color: string;
  /** Formats a plotted value for tooltips, tables, and the popover. */
  format: (n: number) => string;
  /**
   * Formats a y-axis tick, in compact notation. Only set where `format` is too
   * wide for an axis — a grouped `1,234,567` or a unit an axis need not repeat.
   * Defaults to `format`, which is already tick-width for percentages and rates.
   */
  formatTick?: (n: number) => string;
  /** The value plotted for a single day. */
  value: (d: UsageDigest) => number;
  /** The card's headline for today; defaults to `format(value(d))`. */
  headline?: (d: UsageDigest) => string;
  /** Small caption under the headline. */
  sub?: (d: UsageDigest) => string | undefined;
  /** Whether a rising value is a regression (cost, tokens) vs. a win (cache). */
  increaseIsBad?: boolean;
  /** Matching field in `UsageDigest.trend` for the day-over-day delta chip. */
  trendField?: string;
}

const fmtBytesLabel = (n: number) => `${fmtInt(n)} B`;

/**
 * Zone every day-bucketed Overview/Trend value is reported in, e.g. `"EDT"`.
 * Distinct from `format.ts`'s `LOCAL_TZ_ABBR`, which is the viewer's own zone
 * and labels individual timestamps. Resolved once, so a window spanning the
 * daylight-saving switch carries the current abbreviation throughout.
 */
export const REPORT_TZ_ABBR = reportTzAbbr();

/** The Overview statistics, in the order they appear on the page. */
export const METRICS: StatMetric[] = [
  {
    key: 'real-input',
    label: 'Real input tokens',
    description: 'Non-cached input tokens sent to the model each day.',
    color: 'var(--accent)',
    format: fmtInt,
    formatTick: fmtCompact,
    value: (d) => d.tokens.realInput,
    trendField: 'realInput',
  },
  {
    key: 'output',
    label: 'Output tokens',
    description: 'Tokens generated by the model each day.',
    color: 'var(--good)',
    format: fmtInt,
    formatTick: fmtCompact,
    value: (d) => d.tokens.output,
    trendField: 'output',
  },
  {
    key: 'cost',
    label: 'Est. cost',
    description: 'Approximate USD spend per day, from token counts and model pricing.',
    color: 'var(--accent-2)',
    format: fmtUsd,
    formatTick: fmtUsdCompact,
    value: (d) => d.cost.total,
    sub: () => 'approx.',
    trendField: 'cost',
  },
  {
    key: 'cost-rate',
    label: 'Cost per token',
    title: 'Cost per million tokens',
    description:
      "Estimated USD per million tokens moved each day, counting the whole prompt and the output. A day's efficiency, independent of its size — cache reads are far cheaper than fresh input, so leaning on the cache pulls this down.",
    color: 'var(--signal)',
    format: fmtUsdPerMTok,
    value: (d) => costPerMTok(d),
    sub: () => 'blended',
    increaseIsBad: true,
    trendField: 'costPerMTok',
  },
  {
    key: 'cache-hit',
    label: 'Cache-hit ratio',
    description: 'Share of prompt tokens served from cache (cacheRead / realInput) each day.',
    color: 'var(--signal)',
    format: (n) => fmtPct(n),
    value: (d) => d.tokens.cacheHitRatio * 100,
    increaseIsBad: false,
  },
  {
    key: 'requests',
    label: 'Requests',
    description: 'Requests captured per day.',
    color: 'var(--good)',
    format: fmtInt,
    formatTick: fmtCompact,
    value: (d) => d.requestCount,
    trendField: 'requestCount',
  },
  {
    key: 'busiest-hour',
    label: 'Busiest hour',
    title: 'Busiest-hour requests',
    description: `Requests during the single busiest hour of each day (${REPORT_TZ_ABBR}).`,
    color: 'var(--accent)',
    format: (n) => `${fmtInt(n)} req`,
    formatTick: fmtCompact,
    value: (d) => d.busiestHour?.requestCount ?? 0,
    headline: (d) => (d.busiestHour ? `${String(d.busiestHour.hour).padStart(2, '0')}:00` : '—'),
    sub: (d) => (d.busiestHour ? `${d.busiestHour.requestCount} req · ${REPORT_TZ_ABBR}` : undefined),
  },
  {
    key: 'tool-overhead',
    label: 'Tool overhead',
    description: 'Estimated tool-schema tokens as a percentage of input tokens each day.',
    color: 'var(--amber)',
    format: (n) => fmtPct(n),
    value: (d) => d.toolOverheadPctOfInput,
    sub: () => 'of input tokens',
  },
  {
    key: 'avg-system-prompt',
    label: 'Avg system prompt',
    description: 'Mean system-prompt size (bytes) per request each day.',
    color: 'var(--amber)',
    format: fmtBytesLabel,
    formatTick: fmtBytes,
    value: (d) => d.avgSystemPromptBytes,
    trendField: 'avgSystemPromptBytes',
  },
];

const BY_KEY = new Map(METRICS.map((m) => [m.key, m]));

/** Look up a metric by its URL slug. */
export const findMetric = (key: string): StatMetric | undefined => BY_KEY.get(key);
