-- Concept store, schema 1.
--
-- Append-only: every `/teach` run inserts one immutable row and nothing updates
-- or deletes one. Two rows for the same term are two versions, and which one a
-- read returns is decided at read time by `term_key` + `saved_at`.
--
-- `document` carries the record verbatim, which is what preserves the
-- absent-versus-empty distinction on the optional detail fields that the
-- columns beside it cannot express.

CREATE TABLE concept (
  -- ULID, sortable by creation time and generated by the writer. See src/ulid.ts.
  id        TEXT PRIMARY KEY,
  term      TEXT NOT NULL,
  -- Lowercased and whitespace-collapsed. This, not `term`, is what makes two
  -- records the same concept.
  term_key  TEXT NOT NULL,
  sentence  TEXT NOT NULL,
  field     TEXT NOT NULL,
  saved_at  TEXT NOT NULL,
  -- Denormalized so `hasNotes` filters without opening `document`.
  has_notes INTEGER NOT NULL,
  document  TEXT NOT NULL
);

-- The newest-per-term read walks this: equal keys, newest first.
CREATE INDEX concept_term_key ON concept (term_key, saved_at DESC, id DESC);
CREATE INDEX concept_field ON concept (field);
CREATE INDEX concept_saved_at ON concept (saved_at DESC);

-- The skills array gets its own table so a listing can filter or group by skill
-- without unpacking every `document`.
CREATE TABLE concept_skill (
  id        TEXT NOT NULL REFERENCES concept (id) ON DELETE CASCADE,
  skill_ord INTEGER NOT NULL,
  skill     TEXT NOT NULL,
  PRIMARY KEY (id, skill_ord)
);

CREATE INDEX concept_skill_skill ON concept_skill (skill);

-- `tips`, `sources` and `surfacedSkills` share one table, distinguished by `kind`.
CREATE TABLE concept_item (
  id       TEXT NOT NULL REFERENCES concept (id) ON DELETE CASCADE,
  kind     TEXT NOT NULL,
  item_ord INTEGER NOT NULL,
  item     TEXT NOT NULL,
  PRIMARY KEY (id, kind, item_ord)
);

-- Full-text search with bm25 ranking. `id` is UNINDEXED: it is carried so a hit
-- can be joined back to `concept`, not matched against.
CREATE VIRTUAL TABLE concept_fts USING fts5 (
  id UNINDEXED,
  term,
  sentence,
  notes,
  tips
);
