-- Concept store, schema 1.
--
-- Append-only: every `/teach` run inserts one immutable row and nothing ever
-- updates or deletes one. Two rows for the same term are two *versions*; which
-- one a read returns is decided at read time by `term_key` + `saved_at`, never
-- by throwing the older row away.
--
-- `document` carries the record verbatim. That is what preserves the
-- absent-versus-empty distinction on the optional detail fields: the columns
-- beside it cannot express "never recorded" as against "recorded empty", and
-- the detail view depends on the difference.

CREATE TABLE concept (
  -- ULID: sortable by creation time, generated by the writer. See src/ulid.ts
  -- for why this is not an autoincrement.
  id        TEXT PRIMARY KEY,
  term      TEXT NOT NULL,
  -- Lowercased and whitespace-collapsed. This, not `term`, is what makes two
  -- records the same concept, so `Carousel` supersedes `carousel`.
  term_key  TEXT NOT NULL,
  sentence  TEXT NOT NULL,
  field     TEXT NOT NULL,
  saved_at  TEXT NOT NULL,
  -- Denormalized so `hasNotes` filters without opening `document`.
  has_notes INTEGER NOT NULL,
  document  TEXT NOT NULL
);

-- The newest-per-term read walks this: equal keys, newest first.
CREATE INDEX concept_term_key ON concept (term_key, saved_at DESC, id DESC);
CREATE INDEX concept_field ON concept (field);
CREATE INDEX concept_saved_at ON concept (saved_at DESC);

-- The skills array gets its own table so a listing can filter or group by skill
-- without unpacking every `document`.
CREATE TABLE concept_skill (
  id        TEXT NOT NULL REFERENCES concept (id) ON DELETE CASCADE,
  skill_ord INTEGER NOT NULL,
  skill     TEXT NOT NULL,
  PRIMARY KEY (id, skill_ord)
);

CREATE INDEX concept_skill_skill ON concept_skill (skill);

-- `tips`, `sources` and `surfacedSkills` share one table rather than three
-- near-identical ones: only `skill` is a real grouping question, and only it
-- earned a table of its own.
CREATE TABLE concept_item (
  id       TEXT NOT NULL REFERENCES concept (id) ON DELETE CASCADE,
  kind     TEXT NOT NULL,
  item_ord INTEGER NOT NULL,
  item     TEXT NOT NULL,
  PRIMARY KEY (id, kind, item_ord)
);

-- Full-text search with bm25 ranking — the same algorithm okq gets from
-- Tantivy. `id` is UNINDEXED: it is carried so a hit can be joined back to
-- `concept`, not matched against.
CREATE VIRTUAL TABLE concept_fts USING fts5 (
  id UNINDEXED,
  term,
  sentence,
  notes,
  tips
);
